{{- if .Values.priorityClass.enabled }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
{{- $pcSpec := omit .Values.priorityClass "enabled" "name" }}
{{- $pcSpec | toYaml | nindent 0 }}
{{- end }}
