fail_fast: false
minimum_pre_commit_version: '0'
repos:
  # more info on the usage: https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
  - repo: https://github.com/golangci/golangci-lint
    rev: 5d1e709b7be35cb2025444e19de266b056b7b7ee # v2.10.1
    hooks:
      - id: golangci-lint
        stages: [pre-commit]
        language_version: 1.26.0
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 7d85583be209cb547946c82fbe51f4bc5dd1d017 # v18.1.8
    hooks:
      - id: clang-format
        types_or: [c++, c]
        stages: [pre-commit]
