apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-daemon
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: daemon
    {{- include "runtime-enforcer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: daemon
      {{- include "runtime-enforcer.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: daemon
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - args:
        {{- if .Values.telemetry.tracing }}
        - --enable-tracing
        {{- end }}
        {{- if .Values.learning.enabled }}
        - --enable-learning
        {{- end }}
        {{- toYaml .Values.daemon.daemon.args | nindent 8 }}
        command:
        - /daemon
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: CUSTOM_CRI_SOCKET_PATH
            value: {{ .Values.daemon.customCRISocketPath }}
        {{- if or .Values.telemetry.metrics .Values.telemetry.tracing }}
        {{- if eq .Values.telemetry.mode "custom" }}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{.Values.telemetry.custom.endpoint}}
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: {{ .Values.telemetry.custom.insecure | default false | quote }}
        {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorCertificateSecret }}
          - name: OTEL_EXPORTER_OTLP_CERTIFICATE
            value: /tmp/otel-collector-certs/ca.crt 
        {{- end }}
        {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorClientCertificateSecret }}
          - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
            value: /tmp/otel-collector-client-certs/tls.crt
          - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
            value: /tmp/otel-collector-client-certs/tls.key
        {{- end }}
        {{- end }}
        {{- end }}
        image: {{ .Values.daemon.daemon.image.repository }}:{{ .Values.daemon.daemon.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.daemon.daemon.image.pullPolicy }}
        name: daemon
        resources: {{- toYaml .Values.daemon.daemon.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.daemon.daemon.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: crio-socket
          mountPath: /run/crio/crio.sock
          readOnly: true
        - name: containerd-socket
          mountPath: /run/containerd/containerd.sock
          readOnly: true
        - name: dockerd-socket
          mountPath: /var/run/cri-dockerd.sock
          readOnly: true
        - name: nri-socket
          mountPath: /var/run/nri/nri.sock
          mountPropagation: HostToContainer
          readOnly: true
        {{- if .Values.daemon.customCRISocketPath }}
        - name: custom-cri-socket
          mountPath: {{ .Values.daemon.customCRISocketPath }}
          readOnly: true
        {{- end }}
      hostPID: {{ .Values.daemon.hostPID }}
      securityContext: {{- toYaml .Values.daemon.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "runtime-enforcer.fullname" . }}-daemon
      terminationGracePeriodSeconds: 10
      volumes:
      # We try to mount common CRI socket paths. If these are not enough, users should mount the correct socket using criSocketPath value.
      - name: crio-socket
        hostPath:
          path: /run/crio/crio.sock
      - name: containerd-socket
        hostPath:
          path: /run/containerd/containerd.sock
      - name: dockerd-socket
        hostPath:
          path: /run/cri-dockerd.sock
      {{- if .Values.daemon.customCRISocketPath }}
      - name: custom-cri-socket
        hostPath:
          path: {{ .Values.daemon.customCRISocketPath }}
      {{- end }}
      - name: nri-socket
        hostPath:
          path: {{ .Values.daemon.nriSocketPath }}
