github:
  owner: "UPDATECLI_GITHUB_OWNER"
  token: "UPDATECLI_GITHUB_TOKEN"
  branch: "main"
  author: "RuntimeEnforcement bot"
  user: "UPDATECLI_GITHUB_OWNER"
  email: "runtime-enforcement-bot@users.noreply.github.com"
