operator:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/neuvector/runtime-enforcement/operator
      tag: v0.0.2
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
daemon:
  daemon:
    args:
    - ""
    containerSecurityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/neuvector/runtime-enforcement/daemon
      tag: v0.0.2
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local

## Optional array of imagePullSecrets containing private registry credentials
## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

telemetry:
  # Runtime-enforcement telemetry configuration allow two OpenTelemetry
  # collector communication options: 
  # - sidecar: It will create a Otel collector sidecar and configure the
  # controller and policy server to send metrics and traces to it. 
  # - custom: It will configure the controller and policy server to send metrics
  # and traces to a custom collector that is not running as a sidecar.

  # The default configuration is to use the sidecar option. Therefore, if
  # telemetry.metrics or telemetry.tracing are set to true, the sidecar will be
  # deployed. If you want to use a custom collector, set mode to "custom"
  mode: sidecar
  # telemetry.metrics is used to enable/disable the metrics collection and
  # exportation to the OpenTelemetry collector.
  metrics: false
  # telemetry.tracing is used to enable/disable the tracing collection and
  # exportation to the OpenTelemetry collector.
  tracing: false

  # The following settings are mandatory to configure the OpenTelemetry
  # exporter in the controller and policy server to send metrics and traces to
  # a custom collector. These settings are ignored when sidecar mode is used
  custom:
    # telemetry.custom.endpoint is the Otel collector endpoint to send metrics and
    # traces to. It should be in the format https://<hostname>:<port>.
    endpoint: ""
    # telemetry.custom.insecure is used to configure the OpenTelemetry exporter to skip
    # the certificate validation when sending metrics and traces to a remote
    # collector.
    insecure: false
    # The following settings are required to configure the OpenTelemetry exporter
    # in the controller and policy server to send metrics and traces to a remote
    # collector using TLS. Both secrets must be created in the same namespace
    # where the controller is deployed.
    #
    # telemetry.custom.otelCollectorCertificateSecret should contains a key ca.crt
    # storing the certifcate to validate the remote collector certificate.
    otelCollectorCertificateSecret: ""
    # telemetry.custom.otelCollectorClientCertificateSecret secret is optional. It's
    # only required when the remote collector requires client authentication
    # (mTLS). It should contains two keys: tls.crt and tls.key storing the client
    # certificate and key respectively.
    otelCollectorClientCertificateSecret: ""

  # The following settings are used to configure the Prometheus metrics and
  # Jaeger tracing when sidecar mode is used. Otherwise, these settings are ignored 
  sidecar:
    # telemetry.sidecar.metrics is used to configure the Prometheus metrics exporter
    # in the Otel collector sidecar
    metrics:
      # port of the prometheus exporter and PolicyServer metric service
      port: 8080
    # telemetry.sidecar.tracing is used to configure the Jaeger tracing exporter
    # in the Otel collector sidecar
    tracing:
      jaeger: {}
      # OTLP/Jaeger endpoint to send traces to
      # endpoint: "all-in-one-collector.jaeger.svc.cluster.local:4317"
      # tls:
      #  insecure: true

# NOTE: This section is used to configure Tetragon and its components
# deployed by the Tetragon chart dependency.
# Do not edit this section manually.
tetragon:
  tetragon:
    nameOverride: tetragon
    grpc:
      address: unix:///var/run/tetragon/tetragon.sock
  tetragonOperator:
    enabled: false
  crds:
    installMethod: helm
  extraHostPathMounts:
    - name: tetragon-socket
      mountPath: /var/run/tetragon/
