operator:
  manager:
    args:
    - --metrics-bind-address=:8443
    - --leader-elect
    - --health-probe-bind-address=:8081
    containerSecurityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/neuvector/runtime-enforcement/operator
      tag: v0.0.2
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  replicas: 1
  serviceAccount:
    annotations: {}
daemon:
  daemon:
    args:
    - ""
    containerSecurityContext:
      runAsUser: 1000
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/neuvector/runtime-enforcement/daemon
      tag: v0.0.2
      pullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
  podSecurityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  serviceAccount:
    annotations: {}
kubernetesClusterDomain: cluster.local

## Optional array of imagePullSecrets containing private registry credentials
## Ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
imagePullSecrets: []

# NOTE: This section is used to configure Tetragon and its components
# deployed by the Tetragon chart dependency.
# Do not edit this section manually.
tetragon:
  tetragon:
    nameOverride: tetragon
    grpc:
      address: unix:///var/run/tetragon/tetragon.sock
  tetragonOperator:
    enabled: false
  crds:
    installMethod: helm
  extraHostPathMounts:
    - name: tetragon-socket
      mountPath: /var/run/tetragon/
