---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "runtime-enforcer.caIssuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ include "runtime-enforcer.caIssuerName" . }}
  secretName: runtime-enforcer-ca
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "runtime-enforcer.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "runtime-enforcer.caIssuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  ca:
    secretName: runtime-enforcer-ca
