---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-selfsigned-issuer
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  isCA: true
  commonName: {{ include "runtime-enforcer.fullname" . }}-ca
  secretName: runtime-enforcer-ca
  duration: 8736h # 1 year
  renewBefore: 240h # 10 days
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "runtime-enforcer.fullname" . }}-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  ca:
    secretName: runtime-enforcer-ca
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-operator-webhook-tls
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  secretName: {{ include "runtime-enforcer.fullname" . }}-operator-webhook-tls
  dnsNames:
    - {{ include "runtime-enforcer.fullname" . }}-mutating-webhook.{{ .Release.Namespace }}.svc
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: {{ include "runtime-enforcer.fullname" . }}-ca
    kind: Issuer
    group: cert-manager.io
{{- if or .Values.agent.agent.grpc.mTLS }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "runtime-enforcer.grpc.agentSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  secretName: {{ include "runtime-enforcer.grpc.agentSecretName" . }}
  dnsNames:
    # We use a logical name for verification (operator uses this as TLS ServerName)
    - "runtime-enforcer-agent"
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  issuerRef:
    name: {{ include "runtime-enforcer.fullname" . }}-ca
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "runtime-enforcer.grpc.operatorSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  secretName: {{ include "runtime-enforcer.grpc.operatorSecretName" . }}
  commonName: runtime-enforcer-operator
  duration: 2160h # 90 days
  renewBefore: 240h # 10 days
  usages:
    - client auth
  issuerRef:
    name: {{ include "runtime-enforcer.fullname" . }}-ca
    kind: Issuer
    group: cert-manager.io
{{- end }}
