apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.manager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
    {{- include "runtime-enforcer.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
      {{- include "runtime-enforcer.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - args: 
        - --wp-status-reconciler-agent-grpc-port={{ .Values.agent.agent.grpcExporterPort }}
        - --wp-status-reconciler-update-interval={{ .Values.operator.manager.wpStatusUpdateInterval }}
        - --wp-status-reconciler-agent-namespace={{ .Release.Namespace }}
        - --wp-status-reconciler-agent-label-selector=app.kubernetes.io/component=agent
        {{- if .Values.agent.agent.grpc.mTLS }}
        - --wp-status-reconciler-agent-grpc-mtls-enabled=true
        - --wp-status-reconciler-agent-grpc-mtls-cert-dir={{ include "runtime-enforcer.grpc.CertDir" . }}
        {{- end }}
        {{- toYaml .Values.operator.manager.args | nindent 8 }}
        command:
        - /operator
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.operator.manager.image.repository }}:{{ .Values.operator.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.operator.manager.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.operator.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.operator.manager.containerSecurityContext
          | nindent 10 }}
        volumeMounts:
          - mountPath: /tmp/k8s-webhook-server/serving-certs/
            name: webhook-certs
            readOnly: true
          {{- if .Values.agent.agent.grpc.mTLS }}
          - name: grpc-certs
            mountPath: {{ include "runtime-enforcer.grpc.CertDir" . }}
            readOnly: true
          {{- end }}
      volumes:
        - name: webhook-certs
          secret:
            secretName: {{ include "runtime-enforcer.fullname" . }}-operator-webhook-tls
        {{- if .Values.agent.agent.grpc.mTLS }}
        - name: grpc-certs
          secret:
            secretName: {{ include "runtime-enforcer.grpc.operatorSecretName" . }}
        {{- end }}
      securityContext: {{- toYaml .Values.operator.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "runtime-enforcer.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
