{{- if and .Values.operator.pdb .Values.operator.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-controller-manager
  labels:
    {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  {{- $pdbSpec := omit .Values.operator.pdb "enabled" }}
  {{- $pdbSpec | toYaml | nindent 2 }}
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
      {{- include "runtime-enforcer.selectorLabels" . | nindent 6 }}
{{- end }}
