---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-mutating-webhook-configuration
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "runtime-enforcer.caIssuerName" . }}
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "runtime-enforcer.fullname" . }}-mutating-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-security-rancher-io-v1alpha1-workloadpolicyproposal
  failurePolicy: Fail
  name: workloadpolicyproposals.rancher.io
  rules:
  - apiGroups:
    - security.rancher.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloadpolicyproposals
  sideEffects: None
  matchConditions:
  - name: no-selector
    expression: '!has(object.spec.selector) || object.spec.selector.size() == 0'
  - name: no-owner-reference-uid
    expression: '!has(object.metadata.ownerReferences) || object.metadata.ownerReferences.size() == 0 || object.metadata.ownerReferences[0].uid.size() == 0'
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "runtime-enforcer.fullname" . }}-mutating-webhook
      namespace: {{ .Release.Namespace }}
      path: /mutate-security-rancher-io-v1alpha1-workloadpolicy
  failurePolicy: Fail
  name: workloadpolicies.rancher.io
  rules:
  - apiGroups:
    - security.rancher.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workloadpolicies
  sideEffects: None
