apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "runtime-enforcement.fullname" . }}-daemon
  labels:
  {{- include "runtime-enforcement.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: daemon
    {{- include "runtime-enforcement.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: daemon
      {{- include "runtime-enforcement.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: daemon
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - args:
        {{- if .Values.telemetry.tracing }}
        - --enable-tracing
        {{- end }}
        {{- toYaml .Values.daemon.daemon.args | nindent 8 }}
        command:
        - /daemon
        env:
        {{- if or .Values.telemetry.metrics .Values.telemetry.tracing }}
        {{- if eq .Values.telemetry.mode "custom" }}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{.Values.telemetry.custom.endpoint}}
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: {{ .Values.telemetry.custom.insecure | default false | quote }}
        {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorCertificateSecret }}
          - name: OTEL_EXPORTER_OTLP_CERTIFICATE
            value: /tmp/otel-collector-certs/ca.crt 
        {{- end }}
        {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorClientCertificateSecret }}
          - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
            value: /tmp/otel-collector-client-certs/tls.crt
          - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
            value: /tmp/otel-collector-client-certs/tls.key
        {{- end }}
        {{- end }}
        {{- end }}
        image: {{ .Values.daemon.daemon.image.repository }}:{{ .Values.daemon.daemon.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.daemon.daemon.image.pullPolicy }}
        name: daemon
        resources: {{- toYaml .Values.daemon.daemon.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.daemon.daemon.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: tetragon-sock
          mountPath: /var/run/tetragon/
      securityContext: {{- toYaml .Values.daemon.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "runtime-enforcement.fullname" . }}-daemon
      terminationGracePeriodSeconds: 10
      volumes:
      - name: tetragon-sock
        hostPath:
          path: /var/run/tetragon/
