---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "runtime-enforcement.fullname" . }}-daemon
rules:
- apiGroups:
  - security.rancher.io
  resources:
  - workloadsecuritypolicyproposals
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
