apiVersion: v2
name: runtime-enforcer
description: SUSE Security Runtime Enforcer helm chart
type: application
version: 0.1.2
appVersion: v0.1.0

dependencies: []

annotations:
  catalog.cattle.io/certified: rancher # Any application we are adding as a helm chart
  catalog.cattle.io/namespace: cattle-runtime-enforcer-system # Must prefix with cattle- and suffix with -system
  catalog.cattle.io/release-name: rancher-runtime-enforcer # If this is an upstream app, prefixing with rancher is the preferred naming choice.
  catalog.cattle.io/ui-component: runtime-enforcer # This is added for custom UI deployment of a chart
  catalog.cattle.io/display-name: RuntimeEnforcer # Only for Charts with custom UI
  catalog.cattle.io/os: linux # this means linux only, other choice here is "windows". For charts that support both, don't add this annotation
  # optional ones:
  catalog.cattle.io/provides-gvr: "security.rancher.io/v1" # Declare that this chart provides a type, which other charts may use in `requires-gvr`. Only add to parent, not CRD chart.
  # The following two will create a UI warning if the request is not available in cluster
  # Assume the most standard setup for your chart. These can be strings with amounts, ie 64Mi or 2Gi are both valid.
  catalog.cattle.io/requests-cpu: "500m"
  catalog.cattle.io/requests-memory: "128Mi"
  catalog.cattle.io/rancher-version: ">= 2.6.0-0 <= 2.12.100-0" # Chart will only be available for users in the specified Rancher version(s). This _must_ use build metadata or it won't work correctly for future RC's.
  # Valid values for the following annotation include: `cluster-tool`, `app` or `cluster-template`
  # See the Cluster Tools section to learn more about when to set this value to `cluster-tool`.
  catalog.cattle.io/type: cluster-tool
