apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runtime-enforcement.fullname" . }}-controller-manager
  labels:
    control-plane: controller-manager
  {{- include "runtime-enforcement.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.operator.manager.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: operator
    {{- include "runtime-enforcement.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: operator
      {{- include "runtime-enforcement.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: manager
    spec:
      containers:
      - args: {{- toYaml .Values.operator.manager.args | nindent 8 }}
        command:
        - /operator
        env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.operator.manager.image.repository }}:{{ .Values.operator.manager.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.operator.manager.image.pullPolicy }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources: {{- toYaml .Values.operator.manager.resources | nindent 10
          }}
        securityContext: {{- toYaml .Values.operator.manager.containerSecurityContext
          | nindent 10 }}
      securityContext: {{- toYaml .Values.operator.podSecurityContext | nindent
        8 }}
      serviceAccountName: {{ include "runtime-enforcement.fullname" . }}-controller-manager
      terminationGracePeriodSeconds: 10
