apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-agent
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
    {{- include "runtime-enforcer.agent.labelSelector" . | nindent 6 }}
  updateStrategy: 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:
    metadata:
      labels:
      {{- include "runtime-enforcer.agent.labelSelector" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: agent
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - args:
        {{- if .Values.telemetry.tracing }}
        - --enable-tracing
        {{- end }}
        {{- if .Values.learning.enabled }}
        - --enable-learning
        {{- end }}
        - --grpc-port={{ .Values.agent.agent.grpcExporterPort }}
        - --grpc-mtls-cert-dir={{ include "runtime-enforcer.grpc.certDir" . }}
        {{- toYaml .Values.agent.agent.args | nindent 8 }}
        command:
        - /agent
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        {{- if or .Values.telemetry.metrics .Values.telemetry.tracing }}
        {{- if eq .Values.telemetry.mode "custom" }}
          - name: OTEL_EXPORTER_OTLP_ENDPOINT
            value: {{.Values.telemetry.custom.endpoint}}
          - name: OTEL_EXPORTER_OTLP_INSECURE
            value: {{ .Values.telemetry.custom.insecure | default false | quote }}
        {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorCertificateSecret }}
          - name: OTEL_EXPORTER_OTLP_CERTIFICATE
            value: /tmp/otel-collector-certs/ca.crt 
        {{- end }}
        {{- if and (not .Values.telemetry.custom.insecure) .Values.telemetry.custom.otelCollectorClientCertificateSecret }}
          - name: OTEL_EXPORTER_OTLP_CLIENT_CERTIFICATE
            value: /tmp/otel-collector-client-certs/tls.crt
          - name: OTEL_EXPORTER_OTLP_CLIENT_KEY
            value: /tmp/otel-collector-client-certs/tls.key
        {{- end }}
        {{- end }}
        {{- end }}
        image: {{ .Values.agent.agent.image.repository }}:{{ .Values.agent.agent.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.agent.agent.image.pullPolicy }}
        name: agent
        startupProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 3
        resources: {{- toYaml .Values.agent.agent.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.agent.agent.containerSecurityContext | nindent 10 }}
        volumeMounts:
        - name: nri-socket
          mountPath: /var/run/nri/nri.sock
          mountPropagation: HostToContainer
          readOnly: true
        - name: grpc-certs
          mountPath: {{ include "runtime-enforcer.grpc.certDir" . }}
          readOnly: true
      hostPID: {{ .Values.agent.hostPID }}
      securityContext: {{- toYaml .Values.agent.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "runtime-enforcer.fullname" . }}-agent
      terminationGracePeriodSeconds: 10
      volumes:
      - name: nri-socket
        hostPath:
          path: {{ .Values.agent.nriSocketPath }}
      - name: grpc-certs
        csi:
          driver: "csi.cert-manager.io"
          readOnly: true
          volumeAttributes:
            csi.cert-manager.io/issuer-name: {{ include "runtime-enforcer.caIssuerName" . }}
            csi.cert-manager.io/issuer-kind: Issuer
            csi.cert-manager.io/dns-names: ${POD_NAME}.${POD_NAMESPACE}
