apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-agent-rolebinding
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "runtime-enforcer.fullname" . }}-agent'
subjects:
- kind: ServiceAccount
  name: '{{ include "runtime-enforcer.fullname" . }}-agent'
  namespace: '{{ .Release.Namespace }}'
