apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime-enforcer.fullname" . }}-agent
  labels:
  {{- include "runtime-enforcer.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.agent.serviceAccount.annotations | nindent 4 }}
