name: Build, Sign, and Generate SBOM, Attestation & Provenance

on:
  workflow_call:
    inputs:
      version:
        type: string

  push:
    branches:
      - "main"
jobs:
  build:
    strategy:
      matrix:
        component: [operator, daemon]
        arch: [amd64]
        include:
          - arch: amd64
            runner: ubuntu-latest
            platform: linux/amd64
    permissions:
      contents: read
      packages: write # Pushing images to ghcr.io
      id-token: write # Signing images with cosign
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Build image
        uses: ./actions/container-build
        with:
          arch: ${{ matrix.arch }}
          dockerfile: package/Dockerfile.${{ matrix.component }}
          image: ${{ matrix.component }}
          repo: ${{ github.repository }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  merge:
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read # Access private repos
      packages: write # Pushing multi-arch manifest to ghcr.io
      id-token: write # Signing images with cosign
    strategy:
      matrix:
        component: [operator, daemon]
    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - name: Merge images
        uses: ./actions/merge-multiarch
        with:
          arch: amd64
          image: ${{ matrix.component }}
          repo: ${{ github.repository }}
          tag: latest
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
