name: E2E Tests

on:
  pull_request:

jobs:
  test-e2e:
    name: E2E test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: "go.mod"

      - name: Running Test e2e
        run: |
          make test-e2e
      - name: Upload cluster logs
        if: failure()
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
        with:
          name: e2e-test-cluster-logs
          path: test/e2e/logs
          if-no-files-found: error
          retention-days: 7
