name: E2E Tests

on:
  pull_request:

jobs:
  test-e2e:
    name: E2E test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version: "1.24"

      - name: Running Test e2e
        run: |
          make test-e2e
      - name: Upload cluster logs
        if: failure()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: e2e-test-cluster-logs
          path: test/e2e/logs
          if-no-files-found: error
          retention-days: 7
