apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "runtime-enforcement.fullname" . }}-daemon
  labels:
  {{- include "runtime-enforcement.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: daemon
    {{- include "runtime-enforcement.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: daemon
      {{- include "runtime-enforcement.selectorLabels" . | nindent 8 }}
      annotations:
        kubectl.kubernetes.io/default-container: daemon
    spec:
      containers:
      - args: {{- toYaml .Values.daemon.daemon.args | nindent 8 }}
        command:
        - /daemon
        image: {{ .Values.daemon.daemon.image.repository }}:{{ .Values.daemon.daemon.image.tag
          | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.daemon.daemon.image.pullPolicy }}
        name: daemon
        resources: {{- toYaml .Values.daemon.daemon.resources | nindent 10 }}
        securityContext: {{- toYaml .Values.daemon.daemon.containerSecurityContext | nindent 10 }}
      securityContext: {{- toYaml .Values.daemon.podSecurityContext | nindent 8 }}
      serviceAccountName: {{ include "runtime-enforcement.fullname" . }}-daemon
      terminationGracePeriodSeconds: 10
      hostNetwork: true
