apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "runtime-enforcement.fullname" . }}-daemon
  labels:
  {{- include "runtime-enforcement.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.daemon.serviceAccount.annotations | nindent 4 }}
